"""GENERATED by scripts/derive_core_tools.py — do not edit (OT-25).

The core op set: scene-changing ops used successfully in at least
MINIMUM_BRIEFS_USING_OP = 2 distinct gate-passing briefs in
_evaluate/iterations.jsonl. tests/pure/test_tool_disclosure.py asserts
this equals the derivation from the log."""

CORE_OPS = (
    "add_box",  # 3 brief(s)
    "add_cylinder",  # 2 brief(s)
    "assign_material",  # 5 brief(s)
    "boolean_difference",  # 2 brief(s)
    "link_into_scene",  # 5 brief(s)
    "rename_object",  # 2 brief(s)
    "snap_base_to_ground",  # 2 brief(s)
)
